
package subscribeUser;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SubscribeUserService", targetNamespace = "http://soapservice/", wsdlLocation = "http://localhost:8081/subscribeUser?wsdl")
public class SubscribeUserService
    extends Service
{

    private final static URL SUBSCRIBEUSERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(subscribeUser.SubscribeUserService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = subscribeUser.SubscribeUserService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/subscribeUser?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/subscribeUser?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SUBSCRIBEUSERSERVICE_WSDL_LOCATION = url;
    }

    public SubscribeUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscribeUserService() {
        super(SUBSCRIBEUSERSERVICE_WSDL_LOCATION, new QName("http://soapservice/", "SubscribeUserService"));
    }

    /**
     * 
     * @return
     *     returns SubscribeUser
     */
    @WebEndpoint(name = "SubscribeUserPort")
    public SubscribeUser getSubscribeUserPort() {
        return super.getPort(new QName("http://soapservice/", "SubscribeUserPort"), SubscribeUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscribeUser
     */
    @WebEndpoint(name = "SubscribeUserPort")
    public SubscribeUser getSubscribeUserPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soapservice/", "SubscribeUserPort"), SubscribeUser.class, features);
    }

}
