
package getstatistics;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "GetStatistics", targetNamespace = "http://soapservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetStatistics {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatistics", targetNamespace = "http://soapservice/", className = "getstatistics.GetStatistics_Type")
    @ResponseWrapper(localName = "getStatisticsResponse", targetNamespace = "http://soapservice/", className = "getstatistics.GetStatisticsResponse")
    public String getStatistics(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
